name:                cribbage
version:             0.1.0.0
github:              "bitexplorer/cribbage"
license:             BSD3
author:              "Brian Henning"
maintainer:          "henninb@msn.com"
copyright:           "2020 Brian Henning"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/bitexplorer/cribbage#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - pretty-simple
    - random
    - transformers
    - aeson
    - aeson-casing
    - aeson-pretty

executables:
  cribbage-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
     -threaded
     -rtsopts
     -with-rtsopts=-N
    dependencies:
    - cribbage

tests:
  cribbage-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cribbage
    - hspec
