resolver: lts-16.18

packages:
- .

extra-deps:
#  LTS 16.18 for ghc-8.8.4
#  LTS 16.11 for ghc-8.8.3
#  LTS 15.3 for ghc-8.8.2
#  LTS 14.27 for ghc-8.6.5
#  LTS 13.19 for ghc-8.6.4
#  LTS 13.11 for ghc-8.6.3
#  LTS 12.26 for ghc-8.4.4
#  LTS 12.14 for ghc-8.4.3
#  LTS 11.22 for ghc-8.2.2